const standard5stars = [
  { name: "Diluc", rarity: 5 },
  { name: "Jean", rarity: 5 },
  { name: "Mona", rarity: 5 },
  { name: "Qiqi", rarity: 5 },
  { name: "Keqing", rarity: 5 },
  { name: "Tighnari", rarity: 5 },
  { name: "Dehya", rarity: 5 },
   { name: "Yumemizuki Mizuki", rarity: 5 },
];
const limited5stars = [
  { name: "Venti", rarity: 5 },
  { name: "Klee", rarity: 5 },
  { name: "Zhongli", rarity: 5 },
  { name: "Childe", rarity: 5 },
  { name: "Albedo", rarity: 5 },
  { name: "Ganyu", rarity: 5 },
  { name: "Xiao", rarity: 5 },
  { name: "Hu Tao", rarity: 5 },
  { name: "Eula", rarity: 5 },
  { name: "Kaedehara Kazuha", rarity: 5 },
  { name: "Kamisato Ayaka", rarity: 5 },
  { name: "Yoimiya", rarity: 5 },
  { name: "Raiden Shogun", rarity: 5 },
  { name: "Sangonomiya Kokomi", rarity: 5 },
  { name: "Arataki Itto", rarity: 5 },
  { name: "Shenhe", rarity: 5 },
  { name: "Yae Miko", rarity: 5 },
  { name: "Kamisato Ayato", rarity: 5 },
  { name: "Yelan", rarity: 5 },
  { name: "Cyno", rarity: 5 },
  { name: "Nilou", rarity: 5 },
  { name: "Nahida", rarity: 5 },
  { name: "Wanderer", rarity: 5 },
  { name: "Alhaitham", rarity: 5 },
  { name: "Baizhu", rarity: 5 },
  { name: "Lyney", rarity: 5 },
  { name: "Neuvillette", rarity: 5 },
  { name: "Wriothesley", rarity: 5 },
  { name: "Furina", rarity: 5 },
  { name: "Navia", rarity: 5 },
  { name: "Xianyun", rarity: 5 },
  { name: "Chiori", rarity: 5 },
  { name: "Arlecchino", rarity: 5 },
  { name: "Clorinde", rarity: 5 },
  { name: "Sigewinne", rarity: 5 },
  { name: "Emilie", rarity: 5 },
  { name: "Mualani", rarity: 5 },
  { name: "Kinich", rarity: 5 },
  { name: "Xilonen", rarity: 5 },
  { name: "Chasca", rarity: 5 },
  { name: "Mauvika", rarity: 5 },
  { name: "Citlali", rarity: 5 },
  { name: "Varesa", rarity: 5 },
  { name: "Escoffier", rarity: 5 },
  { name: "Skirk", rarity: 5 },
  { name: "Ineffa", rarity: 5 },
  { name: "Lauma", rarity: 5 },
  { name: "Flins", rarity: 5 },
  { name: "Nefer", rarity: 5 },
  { name: "Durin", rarity: 5 },
  { name: "Columbina", rarity: 5 },
  { name: "Zibai", rarity: 5 },
];
const fourStarCharacters = [
  { name: "Amber", rarity: 4 },
  { name: "Kaeya", rarity: 4 },
  { name: "Lisa", rarity: 4 },
  { name: "Barbara", rarity: 4 },
  { name: "Razor", rarity: 4 },
  { name: "Xiangling", rarity: 4 },
  { name: "Beidou", rarity: 4 },
  { name: "Xingqiu", rarity: 4 },
  { name: "Ningguang", rarity: 4 },
  { name: "Fischl", rarity: 4 },
  { name: "Bennett", rarity: 4 },
  { name: "Noelle", rarity: 4 },
  { name: "Chongyun", rarity: 4 },
  { name: "Sucrose", rarity: 4 },
  { name: "Diona", rarity: 4 },
  { name: "Xinyan", rarity: 4 },
  { name: "Rosaria", rarity: 4 },
  { name: "Yanfei", rarity: 4 },
  { name: "Sayu", rarity: 4 },
  { name: "Kujou Sara", rarity: 4 },
  { name: "Thoma", rarity: 4 },
  { name: "Gorou", rarity: 4 },
  { name: "Yun Jin", rarity: 4 },
  { name: "Kuki Shinobu", rarity: 4 },
  { name: "Shikanoin Heizou", rarity: 4 },
  { name: "Collei", rarity: 4 },
  { name: "Dori", rarity: 4 },
  { name: "Candace", rarity: 4 },
  { name: "Layla", rarity: 4 },
  { name: "Faruzan", rarity: 4 },
  { name: "Yaoyao", rarity: 4 },
  { name: "Mika", rarity: 4 },
  { name: "Kaveh", rarity: 4 },
  { name: "Kirara", rarity: 4 },
  { name: "Lynette", rarity: 4 },
  { name: "Freminet", rarity: 4 },
  { name: "Charlotte", rarity: 4 },
  { name: "Chevreuse", rarity: 4 },
  { name: "Gaming", rarity: 4 },
  { name: "Sethos", rarity: 4 },
  { name: "Kachina", rarity: 4 },
  { name: "Ororon", rarity: 4 },
  { name: "Lan Yan", rarity: 4 },
  { name: "Iansan", rarity: 4 },
  { name: "Ifa", rarity: 4 },
  { name: "Dhalia", rarity: 4 },
  { name: "Aino", rarity: 4 },
  { name: "Jahoda", rarity: 4 },
  { name: "Illuga", rarity: 4 },
];
const fourStarWeapons = [
  { name: "Favonius Sword", rarity: 4 },
  { name: "Favonius Lance", rarity: 4 },
  { name: "Favonius Warbow", rarity: 4 },
  { name: "Favonius Codex", rarity: 4 },
  { name: "Favonius Greatsword", rarity: 4 },
  { name: "Sacrificial Sword", rarity: 4 },
  { name: "Sacrificial Bow", rarity: 4 },
  { name: "Sacrificial Fragments", rarity: 4 },
  { name: "Sacrificial Greatsword", rarity: 4 },
  { name: "The Widsith", rarity: 4 },
  { name: "The Stringless", rarity: 4 },
  { name: "Rust", rarity: 4 },
  { name: "Dragon's Bane", rarity: 4 },
  { name: "Lion's Roar", rarity: 4 },
  { name: "The Bell", rarity: 4 },
  { name: "Rainslasher", rarity: 4 },
  { name: "Eye of Perception", rarity: 4 },
  { name: "The Flute", rarity: 4 }
];
const threeStarWeapons = [
  { name: "Amber Catalyst", rarity: 3 },
  { name: "Black Tassel", rarity: 3 },
  { name: "Bloodtainted Greatsword", rarity: 3 },
  { name: "Cool Steel", rarity: 3 },
  { name: "Dark Iron Sword", rarity: 3 },
  { name: "Debate Club", rarity: 3 },
  { name: "Ebony Bow", rarity: 3 },
  { name: "Emerald Orb", rarity: 3 },
  { name: "Ferrous Shadow", rarity: 3 },
  { name: "Fillet Blade", rarity: 3 },
  { name: "Halberd", rarity: 3 },
  { name: "Harbinger of Dawn", rarity: 3 },
  { name: "Magic Guide", rarity: 3 },
  { name: "Messenger", rarity: 3 },
  { name: "Otherworldly Story", rarity: 3 },
  { name: "Quartz", rarity: 3 },
  { name: "Raven Bow", rarity: 3 },
  { name: "Recurve Bow", rarity: 3 },
  { name: "Sharpshooter's Oath", rarity: 3 },
  { name: "Skyrider Greatsword", rarity: 3 },
  { name: "Skyrider Sword", rarity: 3 },
  { name: "Slingshot", rarity: 3 },
  { name: "Thrilling Tales of Dragon Slayers", rarity: 3 },
  { name: "Traveler's Handy Sword", rarity: 3 },
  { name: "Twin Nephrite", rarity: 3 },
  { name: "White Iron Greatsword", rarity: 3 }
];

let pity = 0;
let pullsSinceFour = 0;
