const standard5stars = [
  { name: "Diluc", rarity: 5, image: "diluc_wish.webp" },
  { name: "Jean", rarity: 5, image: "jean_wish.webp" },
  { name: "Mona", rarity: 5, image: "mona_wish.webp" },
  { name: "Qiqi", rarity: 5, image: "qiqi_wish.webp" },
  { name: "Keqing", rarity: 5, image: "keqing_wish.webp" },
  { name: "Tighnari", rarity: 5, image: "tighnari_wish.webp" },
  { name: "Dehya", rarity: 5, image: "dehya_wish.webp" },
  { name: "Yumemizuki Mizuki", rarity: 5, image: "yumemizuki_mizuki_wish.webp" },
];
const limited5stars = [
  { name: "Venti", rarity: 5, image: "venti_wish.webp" },
  { name: "Klee", rarity: 5, image: "klee_wish.webp" },
  { name: "Zhongli", rarity: 5, image: "zhongli_wish.webp" },
  { name: "Tartaglia", rarity: 5, image: "Tartaglia_wish.webp" },
  { name: "Albedo", rarity: 5, image: "albedo.webp" },
  { name: "Ganyu", rarity: 5, image: "ganyu_wish.webp" },
  { name: "Xiao", rarity: 5, image: "xiao_wish.webp" },
  { name: "Hu Tao", rarity: 5, image: "hu_tao_wish.webp" },
  { name: "Eula", rarity: 5, image: "eula_wish.webp" },
  { name: "Kaedehara Kazuha", rarity: 5, image: "kaedehara_kazuha_wish.webp" },
  { name: "Kamisato Ayaka", rarity: 5, image: "kamisato_ayaka_wish.webp" },
  { name: "Yoimiya", rarity: 5, image: "yoimiya_wish.webp" },
  { name: "Raiden Shogun", rarity: 5, image: "raiden_shogun_wish.webp" },
  { name: "Sangonomiya Kokomi", rarity: 5, image: "sangonomiya_kokomi_wish.webp" },
  { name: "Arataki Itto", rarity: 5, image: "itto.webp" },
  { name: "Shenhe", rarity: 5, image: "shenhe_wish.webp" },
  { name: "Yae Miko", rarity: 5, image: "yae_miko_wish.webp" },
  { name: "Kamisato Ayato", rarity: 5, image: "kamisato_ayato_wish.webp" },
  { name: "Yelan", rarity: 5, image: "yelan_wish.webp" },
  { name: "Cyno", rarity: 5, image: "cyno.webp" },
  { name: "Nilou", rarity: 5, image: "nilou_wish.webp" },
  { name: "Nahida", rarity: 5, image: "nahida_wish.webp" },
  { name: "Wanderer", rarity: 5, image: "wanderer_wish.webp" },
  { name: "Alhaitham", rarity: 5, image: "alhaitham.webp" },
  { name: "Baizhu", rarity: 5, image: "baizhu.webp" },
  { name: "Lyney", rarity: 5, image: "lyney_wish.webp" },
  { name: "Neuvillette", rarity: 5, image: "neuvillette_wish.webp" },
  { name: "Wriothesley", rarity: 5, image: "wriothesley_wish.webp" },
  { name: "Furina", rarity: 5, image: "furina_wish.webp" },
  { name: "Navia", rarity: 5, image: "navia_wish.webp" },
  { name: "Xianyun", rarity: 5, image: "xianyun_wish.webp" },
  { name: "Chiori", rarity: 5, image: "chiori_wish.webp" },
  { name: "Arlecchino", rarity: 5, image: "arlecchino_wish.webp" },
  { name: "Clorinde", rarity: 5, image: "clorinde_wish.webp" },
  { name: "Sigewinne", rarity: 5, image: "sigewinne_wish.webp" },
  { name: "Emilie", rarity: 5, image: "emilie_wish.webp" },
  { name: "Mualani", rarity: 5, image: "mualani_wish.webp" },
  { name: "Kinich", rarity: 5, image: "kinich_wish.webp" },
  { name: "Xilonen", rarity: 5, image: "xilonen_wish.webp" },
  { name: "Chasca", rarity: 5, image: "chasca_wish.webp" },
  { name: "Mauvika", rarity: 5, image: "mauvika_wish.webp" },
  { name: "Citlali", rarity: 5, image: "citlali_wish.webp" },
  { name: "Varesa", rarity: 5, image: "varesa_wish.webp" },
  { name: "Escoffier", rarity: 5, image: "escoffier_wish.webp" },
  { name: "Skirk", rarity: 5, image: "skirk_wish.webp" },
  { name: "Ineffa", rarity: 5, image: "ineffa_wish.webp" },
  { name: "Lauma", rarity: 5, image: "lauma_wish.webp" },
  { name: "Flins", rarity: 5, image: "flins_wish.webp" },
  { name: "Nefer", rarity: 5, image: "nefer_wish.webp" },
  { name: "Durin", rarity: 5, image: "durin_wish.webp" },
  { name: "Columbina", rarity: 5, image: "columbina_wish.webp" },
  { name: "Zibai", rarity: 5, image: "zibai_wish.webp" },
];
const fourStarCharacters = [
  { name: "Amber", rarity: 4, image: "amber_wish.webp" },
  { name: "Kaeya", rarity: 4, image: "kaeya_wish.webp" },
  { name: "Lisa", rarity: 4, image: "lisa_wish.webp" },
  { name: "Barbara", rarity: 4, image: "barbara_wish.webp" },
  { name: "Razor", rarity: 4, image: "razor_wish.webp" },
  { name: "Xiangling", rarity: 4, image: "xiangling_wish.webp" },
  { name: "Beidou", rarity: 4, image: "beidou_wish.webp" },
  { name: "Xingqiu", rarity: 4, image: "xingqiu_wish.webp" },
  { name: "Ningguang", rarity: 4, image: "ningguang_wish.webp" },
  { name: "Fischl", rarity: 4, image: "fischl_wish.webp" },
  { name: "Bennett", rarity: 4, image: "bennett_wish.webp" },
  { name: "Noelle", rarity: 4, image: "noelle_wish.webp" },
  { name: "Chongyun", rarity: 4, image: "chongyun_wish.webp" },
  { name: "Sucrose", rarity: 4, image: "sucrose_wish.webp" },
  { name: "Diona", rarity: 4, image: "diona_wish.webp" },
  { name: "Xinyan", rarity: 4, image: "xinyan_wish.webp" },
  { name: "Rosaria", rarity: 4, image: "rosaria_wish.webp" },
  { name: "Yanfei", rarity: 4, image: "yanfei_wish.webp" },
  { name: "Sayu", rarity: 4, image: "sayu_wish.webp" },
  { name: "Kujou Sara", rarity: 4, image: "kujou_sara_wish.webp" },
  { name: "Thoma", rarity: 4, image: "thoma_wish.webp" },
  { name: "Gorou", rarity: 4, image: "gorou_wish.webp" },
  { name: "Yun Jin", rarity: 4, image: "yun_jin_wish.webp" },
  { name: "Kuki Shinobu", rarity: 4, image: "kuki_shinobu_wish.webp" },
  { name: "Shikanoin Heizou", rarity: 4, image: "shikanoin_heizou_wish.webp" },
  { name: "Collei", rarity: 4, image: "collei_wish.webp" },
  { name: "Dori", rarity: 4, image: "dori_wish.webp" },
  { name: "Candace", rarity: 4, image: "candace_wish.webp" },
  { name: "Layla", rarity: 4, image: "layla_wish.webp" },
  { name: "Faruzan", rarity: 4, image: "faruzan_wish.webp" },
  { name: "Yaoyao", rarity: 4, image: "yaoyao_wish.webp" },
  { name: "Mika", rarity: 4, image: "mika_wish.webp" },
  { name: "Kaveh", rarity: 4, image: "kaveh_wish.webp" },
  { name: "Kirara", rarity: 4, image: "kirara_wish.webp" },
  { name: "Lynette", rarity: 4, image: "lynette_wish.webp" },
  { name: "Freminet", rarity: 4, image: "freminet_wish.webp" },
  { name: "Charlotte", rarity: 4, image: "charlotte_wish.webp" },
  { name: "Chevreuse", rarity: 4, image: "chevreuse_wish.webp" },
  { name: "Gaming", rarity: 4, image: "gaming_wish.webp" },
  { name: "Sethos", rarity: 4, image: "sethos_wish.webp" },
  { name: "Kachina", rarity: 4, image: "kachina_wish.webp" },
  { name: "Ororon", rarity: 4, image: "ororon_wish.webp" },
  { name: "Lan Yan", rarity: 4, image: "lan_yan_wish.webp" },
  { name: "Iansan", rarity: 4, image: "iansan_wish.webp" },
  { name: "Ifa", rarity: 4, image: "ifa_wish.webp" },
  { name: "Dhalia", rarity: 4, image: "dhalia_wish.webp" },
  { name: "Aino", rarity: 4, image: "aino_wish.webp" },
  { name: "Jahoda", rarity: 4, image: "jahoda_wish.webp" },
  { name: "Illuga", rarity: 4, image: "illuga_wish.webp" },
];
const fourStarWeapons = [
  { name: "Favonius Sword", rarity: 4, image: "favonius.jpg"},
  { name: "Favonius Lance", rarity: 4 },
  { name: "Favonius Warbow", rarity: 4 },
  { name: "Favonius Codex", rarity: 4 },
  { name: "Favonius Greatsword", rarity: 4 },
  { name: "Sacrificial Sword", rarity: 4 },
  { name: "Sacrificial Bow", rarity: 4 },
  { name: "Sacrificial Fragments", rarity: 4 },
  { name: "Sacrificial Greatsword", rarity: 4 },
  { name: "The Widsith", rarity: 4 },
  { name: "The Stringless", rarity: 4 },
  { name: "Rust", rarity: 4 },
  { name: "Dragon's Bane", rarity: 4 },
  { name: "Lion's Roar", rarity: 4 },
  { name: "The Bell", rarity: 4 },
  { name: "Rainslasher", rarity: 4 },
  { name: "Eye of Perception", rarity: 4 },
  { name: "The Flute", rarity: 4 }
];
const threeStarWeapons = [
  { name: "Amber Catalyst", rarity: 3 },
  { name: "Black Tassel", rarity: 3 },
  { name: "Bloodtainted Greatsword", rarity: 3 },
  { name: "Cool Steel", rarity: 3 },
  { name: "Dark Iron Sword", rarity: 3 },
  { name: "Debate Club", rarity: 3 },
  { name: "Emerald Orb", rarity: 3 },
  { name: "Ferrous Shadow", rarity: 3 },
  { name: "Fillet Blade", rarity: 3 },
  { name: "Halberd", rarity: 3 },
  { name: "Harbinger of Dawn", rarity: 3 },
  { name: "Magic Guide", rarity: 3 },
  { name: "Messenger", rarity: 3 },
  { name: "Otherworldly Story", rarity: 3 },
  { name: "Quartz", rarity: 3 },
  { name: "Raven Bow", rarity: 3 },
  { name: "Recurve Bow", rarity: 3 },
  { name: "Sharpshooter's Oath", rarity: 3 },
  { name: "Skyrider Greatsword", rarity: 3 },
  { name: "Skyrider Sword", rarity: 3 },
  { name: "Slingshot", rarity: 3 },
  { name: "Thrilling Tales of Dragon Slayers", rarity: 3 },
  { name: "Traveler's Handy Sword", rarity: 3 },
  { name: "Twin Nephrite", rarity: 3 },
  { name: "White Iron Greatsword", rarity: 3 }
];

let pity = 0;
let pullsSinceFour = 0;
function random(arr){
  return arr[Math.floor(Math.random()* arr.length)]
}
function wishingpity(){
  pity++
}